image: "rust:1.72"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - target/
    - .cargo

lint:
  before_script:
    - rustc --version && cargo --version # Print version info for debugging
    - rustup component add rustfmt
    - rustfmt --version
    - rustup component add clippy
    - cargo-clippy --version
  script:
    - cargo build
    - cargo fmt --all -- --check
    - cargo clippy -- -D warnings
